-- Insertion de 50 articles de test pour l'entité Article
-- Catégories : 1 (avec sous-catégorie 1-6), 2, 3, 4

-- Articles Catégorie 1 (avec sous-catégories)
INSERT INTO article (nom, description, lieu_fabrication, type_cire, tailles, composition_fabrication, informations_taille_combustion, informations_livraison, actif, created_at, updated_at, categorie_id, sous_categorie_id, temps_combustion_min, temps_combustion_max) VALUES
('Bougie Lavande & Miel', 'Une bougie apaisante qui combine la douceur de la lavande avec les notes sucrées du miel. Parfaite pour vos moments de détente.', 'Provence', 'Cire de soja naturelle', '[{"taille": "S", "prix": 15.90, "barre": 19.90, "combustion": 25, "stock": 15}, {"taille": "M", "prix": 22.90, "barre": 27.90, "combustion": 45, "stock": 10}, {"taille": "L", "prix": 29.90, "combustion": 65, "stock": 5}]', 'Cire de soja 100% naturelle, mèches en coton bio, huiles essentielles de lavande de Provence et essence naturelle de miel.', 'Taille S : 25h de combustion\nTaille M : 45h de combustion\nTaille L : 65h de combustion', 'Livraison en 3-5 jours ouvrés. Emballage soigné et écologique. Livraison offerte dès 50€ d\'achat.', 1, NOW(), NOW(), 1, 1, 25, 65),

('Bougie Vanille Bourbon', 'L\'arôme envoûtant de la vanille bourbon crée une atmosphère chaleureuse et réconfortante dans votre intérieur.', 'Grasse', 'Cire végétale', '[{"taille": "S", "prix": 16.50, "combustion": 30, "stock": 20}, {"taille": "M", "prix": 24.50, "barre": 29.50, "combustion": 50, "stock": 12}, {"taille": "L", "prix": 31.90, "combustion": 70, "stock": 8}]', 'Cire végétale premium, mèche en bois naturel, extrait naturel de vanille bourbon de Madagascar.', 'Taille S : 30h de combustion\nTaille M : 50h de combustion\nTaille L : 70h de combustion', 'Expédition sous 24h. Livraison standard ou express disponible. Emballage cadeau sur demande.', 1, NOW(), NOW(), 1, 2, 30, 70),

('Bougie Fleur d\'Oranger', 'Une senteur délicate et rafraîchissante qui évoque les jardins méditerranéens en pleine floraison.', 'Nice', 'Cire de colza', '[{"taille": "S", "prix": 14.90, "barre": 18.90, "combustion": 22, "stock": 18}, {"taille": "M", "prix": 21.90, "combustion": 42, "stock": 9}, {"taille": "L", "prix": 28.90, "barre": 34.90, "combustion": 62, "stock": 6}]', 'Cire de colza française, mèche en coton, essence naturelle de fleur d\'oranger de Tunisie.', 'Taille S : 22h de combustion\nTaille M : 42h de combustion\nTaille L : 62h de combustion', 'Livraison en France métropolitaine. Colissimo suivi. Protection optimale durant le transport.', 1, NOW(), NOW(), 1, 3, 22, 62),

('Bougie Bois de Santal', 'Un parfum boisé et mystérieux qui apporte une touche d\'élégance orientale à votre espace.', 'Lyon', 'Cire de soja', '[{"taille": "M", "prix": 23.90, "barre": 28.90, "combustion": 48, "stock": 11}, {"taille": "L", "prix": 30.90, "combustion": 68, "stock": 7}, {"taille": "XL", "prix": 39.90, "barre": 45.90, "combustion": 90, "stock": 4}]', 'Cire de soja bio, mèche en coton tressé, huile essentielle de bois de santal d\'Inde.', 'Taille M : 48h de combustion\nTaille L : 68h de combustion\nTaille XL : 90h de combustion', 'Livraison soignée. Possibilité de retrait en boutique. Satisfait ou remboursé 30 jours.', 1, NOW(), NOW(), 1, 4, 48, 90),

('Bougie Rose & Pivoine', 'Un bouquet floral sophistiqué alliant la rose classique aux notes fraîches de la pivoine.', 'Paris', 'Cire végétale premium', '[{"taille": "S", "prix": 17.90, "combustion": 28, "stock": 14}, {"taille": "M", "prix": 25.90, "barre": 31.90, "combustion": 48, "stock": 8}, {"taille": "L", "prix": 33.90, "combustion": 68, "stock": 5}]', 'Cire végétale de haute qualité, mèche en lin, essences florales naturelles de rose de Grasse et pivoine.', 'Taille S : 28h de combustion\nTaille M : 48h de combustion\nTaille L : 68h de combustion', 'Expédition rapide. Emballage luxe inclus. Carte de vœux personnalisable offerte.', 1, NOW(), NOW(), 1, 5, 28, 68),

('Bougie Figuier & Cèdre', 'Une composition originale mariant la douceur du figuier à la puissance du cèdre pour une ambiance unique.', 'Marseille', 'Cire de coco', '[{"taille": "S", "prix": 15.50, "barre": 19.50, "combustion": 24, "stock": 16}, {"taille": "M", "prix": 22.50, "combustion": 44, "stock": 10}, {"taille": "L", "prix": 29.50, "barre": 35.50, "combustion": 64, "stock": 6}]', 'Cire de coco naturelle, mèche en chanvre, extraits naturels de figuier et essence de cèdre.', 'Taille S : 24h de combustion\nTaille M : 44h de combustion\nTaille L : 64h de combustion', 'Livraison en point relais ou à domicile. Emballage recyclable. Fabrication artisanale française.', 1, NOW(), NOW(), 1, 6, 24, 64),

('Bougie Thé Vert & Bergamote', 'Une fragrance vivifiante et tonique qui apporte fraîcheur et énergie à votre quotidien.', 'Bordeaux', 'Cire de soja', '[{"taille": "S", "prix": 16.90, "combustion": 26, "stock": 17}, {"taille": "M", "prix": 23.90, "barre": 28.90, "combustion": 46, "stock": 11}, {"taille": "L", "prix": 30.90, "combustion": 66, "stock": 7}]', 'Cire de soja écologique, mèche en coton bio, extrait de thé vert du Japon et essence de bergamote d\'Italie.', 'Taille S : 26h de combustion\nTaille M : 46h de combustion\nTaille L : 66h de combustion', 'Livraison suivie. Retour gratuit sous 14 jours. Service client disponible 7j/7.', 1, NOW(), NOW(), 1, 2, 26, 66),

('Bougie Jasmin de Nuit', 'Un parfum enivrant et sensuel qui évoque les soirées d\'été sous les étoiles.', 'Cannes', 'Cire végétale', '[{"taille": "M", "prix": 24.90, "combustion": 47, "stock": 9}, {"taille": "L", "prix": 31.90, "barre": 37.90, "combustion": 67, "stock": 6}, {"taille": "XL", "prix": 41.90, "combustion": 92, "stock": 3}]', 'Cire végétale fine, mèche en lin tressé, absolue de jasmin d\'Égypte.', 'Taille M : 47h de combustion\nTaille L : 67h de combustion\nTaille XL : 92h de combustion', 'Expédition sécurisée. Livraison en France et Europe. Garantie qualité artisanale.', 1, NOW(), NOW(), 1, 1, 47, 92),

-- Articles Catégorie 2
('Bougie Citron Vert & Basilic', 'Une association fraîche et herbacée qui purifie l\'atmosphère et stimule les sens.', 'Toulouse', 'Cire de soja', '[{"taille": "S", "prix": 14.50, "barre": 17.50, "combustion": 23, "stock": 19}, {"taille": "M", "prix": 21.50, "combustion": 43, "stock": 13}, {"taille": "L", "prix": 28.50, "combustion": 63, "stock": 8}]', 'Cire de soja naturelle, mèche en coton, huiles essentielles de citron vert et basilic frais.', 'Taille S : 23h de combustion\nTaille M : 43h de combustion\nTaille L : 63h de combustion', 'Livraison express disponible. Emballage écologique. Production locale et responsable.', 1, NOW(), NOW(), 2, NULL, 23, 63),

('Bougie Ambre & Musc', 'Un parfum profond et mystérieux aux notes orientales qui crée une ambiance chaleureuse.', 'Montpellier', 'Cire végétale', '[{"taille": "S", "prix": 17.50, "combustion": 27, "stock": 15}, {"taille": "M", "prix": 25.50, "barre": 30.50, "combustion": 47, "stock": 9}, {"taille": "L", "prix": 33.50, "barre": 39.50, "combustion": 67, "stock": 5}]', 'Cire végétale premium, mèche en bois de cerisier, essences d\'ambre gris et musc blanc.', 'Taille S : 27h de combustion\nTaille M : 47h de combustion\nTaille L : 67h de combustion', 'Livraison soignée dans toute la France. Emballage cadeau luxe offert. Retour facile.', 1, NOW(), NOW(), 2, NULL, 27, 67),

('Bougie Patchouli & Vétiver', 'Une fragrance terreuse et enveloppante qui apporte sérénité et connexion avec la nature.', 'Nantes', 'Cire de colza', '[{"taille": "M", "prix": 22.90, "combustion": 45, "stock": 12}, {"taille": "L", "prix": 29.90, "barre": 34.90, "combustion": 65, "stock": 7}, {"taille": "XL", "prix": 38.90, "combustion": 88, "stock": 4}]', 'Cire de colza française, mèche en coton bio, huiles essentielles de patchouli d\'Indonésie et vétiver d\'Haïti.', 'Taille M : 45h de combustion\nTaille L : 65h de combustion\nTaille XL : 88h de combustion', 'Livraison en 48h. Emballage biodégradable. Fabrication artisanale dans le respect de l\'environnement.', 1, NOW(), NOW(), 2, NULL, 45, 88),

('Bougie Eucalyptus & Menthe', 'Un souffle de fraîcheur intense qui purifie l\'air et revigore l\'esprit.', 'Strasbourg', 'Cire de soja', '[{"taille": "S", "prix": 15.90, "barre": 19.90, "combustion": 25, "stock": 18}, {"taille": "M", "prix": 22.90, "combustion": 45, "stock": 10}, {"taille": "L", "prix": 29.90, "combustion": 65, "stock": 6}]', 'Cire de soja bio, mèche en coton, huiles essentielles d\'eucalyptus d\'Australie et menthe poivrée.', 'Taille S : 25h de combustion\nTaille M : 45h de combustion\nTaille L : 65h de combustion', 'Expédition rapide. Livraison suivie. Emballage soigné et recyclable.', 1, NOW(), NOW(), 2, NULL, 25, 65),

('Bougie Pin Sylvestre', 'L\'essence authentique de la forêt nordique pour une atmosphère naturelle et ressourçante.', 'Lille', 'Cire végétale', '[{"taille": "S", "prix": 16.50, "combustion": 26, "stock": 16}, {"taille": "M", "prix": 24.50, "barre": 29.50, "combustion": 46, "stock": 11}, {"taille": "L", "prix": 32.50, "combustion": 66, "stock": 7}]', 'Cire végétale naturelle, mèche en lin, résine et aiguilles de pin sylvestre de Scandinavie.', 'Taille S : 26h de combustion\nTaille M : 46h de combustion\nTaille L : 66h de combustion', 'Livraison en France métropolitaine. Emballage écologique. Garantie satisfaction.', 1, NOW(), NOW(), 2, NULL, 26, 66),

('Bougie Encens & Myrrhe', 'Un parfum sacré et envoûtant qui évoque les rituels ancestraux et la méditation.', 'Rennes', 'Cire de coco', '[{"taille": "M", "prix": 23.50, "combustion": 46, "stock": 10}, {"taille": "L", "prix": 30.50, "barre": 36.50, "combustion": 66, "stock": 6}, {"taille": "XL", "prix": 40.50, "barre": 47.50, "combustion": 91, "stock": 3}]', 'Cire de coco pure, mèche en chanvre, résines naturelles d\'encens d\'Oman et myrrhe d\'Éthiopie.', 'Taille M : 46h de combustion\nTaille L : 66h de combustion\nTaille XL : 91h de combustion', 'Livraison sécurisée. Emballage luxe. Production artisanale française certifiée.', 1, NOW(), NOW(), 2, NULL, 46, 91),

('Bougie Cèdre de l\'Atlas', 'Un parfum boisé puissant et noble qui apporte caractère et profondeur à votre intérieur.', 'Dijon', 'Cire de soja', '[{"taille": "S", "prix": 15.90, "combustion": 24, "stock": 17}, {"taille": "M", "prix": 23.90, "barre": 28.90, "combustion": 44, "stock": 12}, {"taille": "L", "prix": 31.90, "combustion": 64, "stock": 8}]', 'Cire de soja écologique, mèche en coton bio, huile essentielle de cèdre de l\'Atlas du Maroc.', 'Taille S : 24h de combustion\nTaille M : 44h de combustion\nTaille L : 64h de combustion', 'Livraison en point relais ou domicile. Retour gratuit. Fabrication française artisanale.', 1, NOW(), NOW(), 2, NULL, 24, 64),

('Bougie Agrumes Méditerranéens', 'Un mélange pétillant d\'orange, citron et pamplemousse pour une énergie solaire.', 'Toulon', 'Cire végétale', '[{"taille": "S", "prix": 14.90, "barre": 18.90, "combustion": 23, "stock": 20}, {"taille": "M", "prix": 21.90, "combustion": 43, "stock": 14}, {"taille": "L", "prix": 28.90, "barre": 33.90, "combustion": 63, "stock": 9}]', 'Cire végétale naturelle, mèche en coton, zestes d\'orange de Sicile, citron de Menton et pamplemousse.', 'Taille S : 23h de combustion\nTaille M : 43h de combustion\nTaille L : 63h de combustion', 'Expédition sous 24h. Livraison suivie. Emballage éco-responsable.', 1, NOW(), NOW(), 2, NULL, 23, 63),

-- Articles Catégorie 3
('Bougie Caramel Beurre Salé', 'Une gourmandise irrésistible aux notes sucrées et salées qui évoque les délices bretons.', 'Saint-Malo', 'Cire de soja', '[{"taille": "S", "prix": 16.90, "combustion": 27, "stock": 15}, {"taille": "M", "prix": 24.90, "barre": 29.90, "combustion": 47, "stock": 10}, {"taille": "L", "prix": 32.90, "combustion": 67, "stock": 6}]', 'Cire de soja naturelle, mèche en coton, arômes naturels de caramel et sel de Guérande.', 'Taille S : 27h de combustion\nTaille M : 47h de combustion\nTaille L : 67h de combustion', 'Livraison soignée. Emballage cadeau disponible. Production artisanale bretonne.', 1, NOW(), NOW(), 3, NULL, 27, 67),

('Bougie Café Expresso', 'L\'arôme authentique d\'un café fraîchement moulu pour les amateurs de cette boisson divine.', 'Annecy', 'Cire végétale', '[{"taille": "S", "prix": 15.50, "barre": 19.50, "combustion": 25, "stock": 18}, {"taille": "M", "prix": 22.50, "combustion": 45, "stock": 11}, {"taille": "L", "prix": 29.50, "barre": 34.50, "combustion": 65, "stock": 7}]', 'Cire végétale premium, mèche en bois, grains de café arabica torréfiés et moulus.', 'Taille S : 25h de combustion\nTaille M : 45h de combustion\nTaille L : 65h de combustion', 'Livraison express disponible. Emballage écologique. Garantie fraîcheur.', 1, NOW(), NOW(), 3, NULL, 25, 65),

('Bougie Chocolat Noir', 'Un parfum gourmand et intense de chocolat noir à 70% de cacao pour les épicuriens.', 'Grenoble', 'Cire de coco', '[{"taille": "M", "prix": 23.90, "combustion": 46, "stock": 12}, {"taille": "L", "prix": 30.90, "barre": 36.90, "combustion": 66, "stock": 8}, {"taille": "XL", "prix": 39.90, "combustion": 89, "stock": 4}]', 'Cire de coco naturelle, mèche en chanvre, extrait naturel de fèves de cacao de Madagascar.', 'Taille M : 46h de combustion\nTaille L : 66h de combustion\nTaille XL : 89h de combustion', 'Livraison en 48h. Emballage premium. Cadeau idéal pour les gourmands.', 1, NOW(), NOW(), 3, NULL, 46, 89),

('Bougie Tarte Tatin', 'Les arômes chaleureux de pommes caramélisées et de pâte croustillante comme chez grand-mère.', 'Orléans', 'Cire de soja', '[{"taille": "S", "prix": 16.50, "combustion": 26, "stock": 16}, {"taille": "M", "prix": 24.50, "barre": 29.50, "combustion": 46, "stock": 9}, {"taille": "L", "prix": 32.50, "combustion": 66, "stock": 5}]', 'Cire de soja bio, mèche en coton, arômes naturels de pomme, cannelle et caramel.', 'Taille S : 26h de combustion\nTaille M : 46h de combustion\nTaille L : 66h de combustion', 'Livraison France entière. Emballage soigné. Fabrication artisanale française.', 1, NOW(), NOW(), 3, NULL, 26, 66),

('Bougie Pain d\'Épices', 'Un parfum festif aux épices douces qui évoque les marchés de Noël et la convivialité.', 'Colmar', 'Cire végétale', '[{"taille": "S", "prix": 15.90, "barre": 19.90, "combustion": 24, "stock": 19}, {"taille": "M", "prix": 23.90, "combustion": 44, "stock": 13}, {"taille": "L", "prix": 31.90, "barre": 37.90, "combustion": 64, "stock": 8}]', 'Cire végétale naturelle, mèche en lin, cannelle, gingembre, anis étoilé et miel.', 'Taille S : 24h de combustion\nTaille M : 44h de combustion\nTaille L : 64h de combustion', 'Expédition rapide. Emballage festif. Parfait pour les fêtes de fin d\'année.', 1, NOW(), NOW(), 3, NULL, 24, 64),

('Bougie Brioche Vanillée', 'L\'odeur réconfortante d\'une brioche chaude sortant du four avec ses notes beurrées.', 'Rouen', 'Cire de soja', '[{"taille": "S", "prix": 14.90, "combustion": 23, "stock": 17}, {"taille": "M", "prix": 22.90, "barre": 27.90, "combustion": 43, "stock": 12}, {"taille": "L", "prix": 30.90, "combustion": 63, "stock": 7}]', 'Cire de soja naturelle, mèche en coton bio, arômes de brioche, beurre frais et vanille.', 'Taille S : 23h de combustion\nTaille M : 43h de combustion\nTaille L : 63h de combustion', 'Livraison soignée. Emballage recyclable. Production locale normande.', 1, NOW(), NOW(), 3, NULL, 23, 63),

('Bougie Confiture de Fraises', 'Un parfum fruité et sucré qui rappelle les petits déjeuners d\'été à la campagne.', 'Périgueux', 'Cire de colza', '[{"taille": "M", "prix": 21.90, "combustion": 44, "stock": 11}, {"taille": "L", "prix": 28.90, "barre": 33.90, "combustion": 64, "stock": 8}, {"taille": "XL", "prix": 37.90, "combustion": 87, "stock": 5}]', 'Cire de colza française, mèche en coton, essence naturelle de fraises du Périgord.', 'Taille M : 44h de combustion\nTaille L : 64h de combustion\nTaille XL : 87h de combustion', 'Livraison en France métropolitaine. Emballage cadeau offert. Artisanat du terroir.', 1, NOW(), NOW(), 3, NULL, 44, 87),

('Bougie Madeleine au Citron', 'Les saveurs délicates de la madeleine traditionnelle relevées par une touche citronnée.', 'Commercy', 'Cire végétale', '[{"taille": "S", "prix": 15.50, "barre": 18.50, "combustion": 25, "stock": 15}, {"taille": "M", "prix": 23.50, "combustion": 45, "stock": 10}, {"taille": "L", "prix": 31.50, "barre": 36.50, "combustion": 65, "stock": 6}]', 'Cire végétale premium, mèche en lin, arômes de madeleine, beurre et zeste de citron.', 'Taille S : 25h de combustion\nTaille M : 45h de combustion\nTaille L : 65h de combustion', 'Expédition sous 24h. Emballage soigné. Recette artisanale lorraine.', 1, NOW(), NOW(), 3, NULL, 25, 65),

-- Articles Catégorie 4
('Bougie Océan Atlantique', 'Une brise marine fraîche et iodée qui évoque les promenades au bord de l\'océan.', 'La Rochelle', 'Cire de soja', '[{"taille": "S", "prix": 16.90, "combustion": 26, "stock": 16}, {"taille": "M", "prix": 24.90, "barre": 29.90, "combustion": 46, "stock": 10}, {"taille": "L", "prix": 32.90, "combustion": 66, "stock": 7}]', 'Cire de soja naturelle, mèche en coton, accord marin aux notes d\'algues et sel de mer.', 'Taille S : 26h de combustion\nTaille M : 46h de combustion\nTaille L : 66h de combustion', 'Livraison en France et DOM-TOM. Emballage maritime. Fabrication artisanale côtière.', 1, NOW(), NOW(), 4, NULL, 26, 66),

('Bougie Forêt de Bambou', 'Une fragrance verte et zen qui apporte sérénité et équilibre dans votre espace.', 'Angers', 'Cire végétale', '[{"taille": "S", "prix": 15.90, "barre": 19.90, "combustion": 25, "stock": 18}, {"taille": "M", "prix": 23.90, "combustion": 45, "stock": 12}, {"taille": "L", "prix": 31.90, "barre": 37.90, "combustion": 65, "stock": 8}]', 'Cire végétale naturelle, mèche en chanvre, essence de bambou et feuilles de thé vert.', 'Taille S : 25h de combustion\nTaille M : 45h de combustion\nTaille L : 65h de combustion', 'Livraison rapide. Emballage zen. Philosophie de bien-être et respect de la nature.', 1, NOW(), NOW(), 4, NULL, 25, 65),

('Bougie Pluie d\'Été', 'L\'odeur caractéristique de la terre après la pluie, apaisante et rafraîchissante.', 'Poitiers', 'Cire de coco', '[{"taille": "M", "prix": 22.90, "combustion": 45, "stock": 11}, {"taille": "L", "prix": 29.90, "barre": 34.90, "combustion": 65, "stock": 7}, {"taille": "XL", "prix": 38.90, "combustion": 88, "stock": 4}]', 'Cire de coco pure, mèche en coton bio, accord pétrichor et notes vertes aquatiques.', 'Taille M : 45h de combustion\nTaille L : 65h de combustion\nTaille XL : 88h de combustion', 'Livraison soignée. Emballage écologique. Création originale et poétique.', 1, NOW(), NOW(), 4, NULL, 45, 88),

('Bougie Jardin d\'Herbes', 'Un mélange aromatique de basilic, romarin et thym qui évoque le potager provençal.', 'Avignon', 'Cire de soja', '[{"taille": "S", "prix": 14.90, "barre": 17.90, "combustion": 24, "stock": 19}, {"taille": "M", "prix": 21.90, "combustion": 44, "stock": 13}, {"taille": "L", "prix": 28.90, "combustion": 64, "stock": 9}]', 'Cire de soja bio, mèche en coton, huiles essentielles de basilic, romarin et thym de Provence.', 'Taille S : 24h de combustion\nTaille M : 44h de combustion\nTaille L : 64h de combustion', 'Livraison France métropolitaine. Emballage provençal. Savoir-faire artisanal du Sud.', 1, NOW(), NOW(), 4, NULL, 24, 64),

('Bougie Foin Coupé', 'Une senteur champêtre authentique qui rappelle les étés à la ferme et les champs dorés.', 'Limoges', 'Cire végétale', '[{"taille": "S", "prix": 15.50, "combustion": 25, "stock": 17}, {"taille": "M", "prix": 23.50, "barre": 28.50, "combustion": 45, "stock": 11}, {"taille": "L", "prix": 31.50, "combustion": 65, "stock": 6}]', 'Cire végétale naturelle, mèche en lin, essence de foin frais et herbes des prés.', 'Taille S : 25h de combustion\nTaille M : 45h de combustion\nTaille L : 65h de combustion', 'Expédition rapide. Emballage rustique. Fabrication artisanale du Limousin.', 1, NOW(), NOW(), 4, NULL, 25, 65),

('Bougie Sous-Bois Automnal', 'Les senteurs profondes de la forêt en automne : mousse, champignons et feuilles humides.', 'Clermont-Ferrand', 'Cire de colza', '[{"taille": "M", "prix": 22.50, "combustion": 46, "stock": 10}, {"taille": "L", "prix": 29.50, "barre": 35.50, "combustion": 66, "stock": 7}, {"taille": "XL", "prix": 39.50, "barre": 46.50, "combustion": 90, "stock": 3}]', 'Cire de colza française, mèche en coton, accord boisé de mousse, humus et champignons.', 'Taille M : 46h de combustion\nTaille L : 66h de combustion\nTaille XL : 90h de combustion', 'Livraison soignée. Emballage automnal. Production artisanale auvergnate.', 1, NOW(), NOW(), 4, NULL, 46, 90),

('Bougie Fleur de Coton', 'Une senteur douce et poudrée qui évoque la pureté et le confort du linge frais.', 'Amiens', 'Cire de soja', '[{"taille": "S", "prix": 16.50, "barre": 20.50, "combustion": 26, "stock": 15}, {"taille": "M", "prix": 24.50, "combustion": 46, "stock": 9}, {"taille": "L", "prix": 32.50, "barre": 38.50, "combustion": 66, "stock": 5}]', 'Cire de soja naturelle, mèche en coton bio, accord floral poudreux aux notes de muguet.', 'Taille S : 26h de combustion\nTaille M : 46h de combustion\nTaille L : 66h de combustion', 'Livraison en France. Emballage doux et élégant. Création artisanale picarde.', 1, NOW(), NOW(), 4, NULL, 26, 66),

('Bougie Bois Flotté', 'Un parfum marin et boisé qui capture l\'essence des trésors échoués sur la plage.', 'Brest', 'Cire végétale', '[{"taille": "S", "prix": 15.90, "combustion": 25, "stock": 16}, {"taille": "M", "prix": 23.90, "barre": 28.90, "combustion": 45, "stock": 11}, {"taille": "L", "prix": 31.90, "combustion": 65, "stock": 7}]', 'Cire végétale premium, mèche en chanvre, accord boisé marin avec notes iodées et ambrées.', 'Taille S : 25h de combustion\nTaille M : 45h de combustion\nTaille L : 65h de combustion', 'Expédition rapide. Emballage maritime. Artisanat breton de qualité.', 1, NOW(), NOW(), 4, NULL, 25, 65),

-- Articles supplémentaires variés
('Bougie Néroli & Mandarine', 'Un duo d\'agrumes ensoleillés et floraux pour une atmosphère méditerranéenne raffinée.', 'Menton', 'Cire de soja', '[{"taille": "S", "prix": 17.50, "combustion": 28, "stock": 14}, {"taille": "M", "prix": 25.50, "barre": 30.50, "combustion": 48, "stock": 9}, {"taille": "L", "prix": 33.50, "combustion": 68, "stock": 5}]', 'Cire de soja bio, mèche en coton, essence de néroli de Tunisie et mandarine de Corse.', 'Taille S : 28h de combustion\nTaille M : 48h de combustion\nTaille L : 68h de combustion', 'Livraison express. Emballage méditerranéen. Fabrication artisanale de la Côte d\'Azur.', 1, NOW(), NOW(), 1, 3, 28, 68),

('Bougie Oud & Safran', 'Un parfum luxueux et mystérieux aux notes précieuses orientales pour une ambiance raffinée.', 'Versailles', 'Cire végétale premium', '[{"taille": "M", "prix": 29.90, "barre": 35.90, "combustion": 50, "stock": 8}, {"taille": "L", "prix": 39.90, "combustion": 70, "stock": 5}, {"taille": "XL", "prix": 49.90, "barre": 59.90, "combustion": 95, "stock": 3}]', 'Cire végétale de luxe, mèche en bois de santal, essence d\'oud cambodgien et filaments de safran.', 'Taille M : 50h de combustion\nTaille L : 70h de combustion\nTaille XL : 95h de combustion', 'Livraison premium. Emballage luxe. Collection prestige pour connaisseurs.', 1, NOW(), NOW(), 2, NULL, 50, 95),

('Bougie Thym Citronné', 'Une fragrance herbacée et citronnée qui purifie l\'air et éveille les sens.', 'Aix-en-Provence', 'Cire de colza', '[{"taille": "S", "prix": 14.50, "barre": 17.50, "combustion": 23, "stock": 18}, {"taille": "M", "prix": 21.50, "combustion": 43, "stock": 12}, {"taille": "L", "prix": 28.50, "barre": 33.50, "combustion": 63, "stock": 8}]', 'Cire de colza bio, mèche en coton, huile essentielle de thym citronné de Provence.', 'Taille S : 23h de combustion\nTaille M : 43h de combustion\nTaille L : 63h de combustion', 'Livraison soignée. Emballage provençal. Production locale et naturelle.', 1, NOW(), NOW(), 4, NULL, 23, 63),

('Bougie Noix de Coco', 'Un parfum exotique et gourmand qui évoque les plages tropicales et les vacances.', 'Fort-de-France', 'Cire de coco', '[{"taille": "S", "prix": 16.90, "combustion": 27, "stock": 15}, {"taille": "M", "prix": 24.90, "barre": 29.90, "combustion": 47, "stock": 10}, {"taille": "L", "prix": 32.90, "combustion": 67, "stock": 6}]', 'Cire de coco naturelle, mèche en coton, extrait naturel de noix de coco fraîche.', 'Taille S : 27h de combustion\nTaille M : 47h de combustion\nTaille L : 67h de combustion', 'Livraison France et Outre-mer. Emballage tropical. Fabrication artisanale antillaise.', 1, NOW(), NOW(), 3, NULL, 27, 67),

('Bougie Pivoine & Litchi', 'Une association délicate et gourmande entre fleur et fruit pour une ambiance romantique.', 'Tours', 'Cire de soja', '[{"taille": "S", "prix": 17.90, "barre": 21.90, "combustion": 28, "stock": 13}, {"taille": "M", "prix": 25.90, "combustion": 48, "stock": 8}, {"taille": "L", "prix": 33.90, "barre": 39.90, "combustion": 68, "stock": 5}]', 'Cire de soja naturelle, mèche en lin, essence de pivoine et extrait naturel de litchi.', 'Taille S : 28h de combustion\nTaille M : 48h de combustion\nTaille L : 68h de combustion', 'Expédition rapide. Emballage fleuri. Création artisanale romantique.', 1, NOW(), NOW(), 1, 5, 28, 68),

('Bougie Tabac Blond', 'Un parfum sophistiqué et enveloppant aux notes de tabac doux, miel et vanille.', 'Cognac', 'Cire végétale', '[{"taille": "M", "prix": 26.90, "combustion": 49, "stock": 9}, {"taille": "L", "prix": 34.90, "barre": 40.90, "combustion": 69, "stock": 6}, {"taille": "XL", "prix": 44.90, "combustion": 93, "stock": 3}]', 'Cire végétale premium, mèche en bois, accord de tabac blond, miel et vanille bourbon.', 'Taille M : 49h de combustion\nTaille L : 69h de combustion\nTaille XL : 93h de combustion', 'Livraison soignée. Emballage élégant. Collection signature charentaise.', 1, NOW(), NOW(), 2, NULL, 49, 93),

('Bougie Poire Williams', 'Le parfum juteux et sucré de la poire Williams pour une touche fruitée et gourmande.', 'Valence', 'Cire de soja', '[{"taille": "S", "prix": 15.50, "combustion": 25, "stock": 17}, {"taille": "M", "prix": 23.50, "barre": 28.50, "combustion": 45, "stock": 11}, {"taille": "L", "prix": 31.50, "combustion": 65, "stock": 7}]', 'Cire de soja bio, mèche en coton, essence naturelle de poire Williams de la Drôme.', 'Taille S : 25h de combustion\nTaille M : 45h de combustion\nTaille L : 65h de combustion', 'Livraison France métropolitaine. Emballage fruité. Artisanat du terroir drômois.', 1, NOW(), NOW(), 3, NULL, 25, 65),

('Bougie Fleur de Magnolia', 'Une senteur florale somptueuse et élégante qui apporte raffinement et douceur.', 'Angers', 'Cire végétale', '[{"taille": "S", "prix": 18.90, "barre": 23.90, "combustion": 29, "stock": 12}, {"taille": "M", "prix": 26.90, "combustion": 49, "stock": 8}, {"taille": "L", "prix": 34.90, "barre": 41.90, "combustion": 69, "stock": 4}]', 'Cire végétale fine, mèche en lin tressé, essence de magnolia de Chine.', 'Taille S : 29h de combustion\nTaille M : 49h de combustion\nTaille L : 69h de combustion', 'Expédition soignée. Emballage luxe. Production artisanale angevine.', 1, NOW(), NOW(), 1, 1, 29, 69),

('Bougie Bois de Oud & Rose', 'Une combinaison précieuse et orientale entre le mystérieux oud et la rose damascène.', 'Grasse', 'Cire de coco premium', '[{"taille": "M", "prix": 28.90, "barre": 34.90, "combustion": 50, "stock": 7}, {"taille": "L", "prix": 37.90, "combustion": 70, "stock": 5}, {"taille": "XL", "prix": 47.90, "barre": 55.90, "combustion": 94, "stock": 2}]', 'Cire de coco premium, mèche en bois précieux, oud royal et absolue de rose de Grasse.', 'Taille M : 50h de combustion\nTaille L : 70h de combustion\nTaille XL : 94h de combustion', 'Livraison premium. Emballage prestige. Collection haute parfumerie grassoise.', 1, NOW(), NOW(), 2, NULL, 50, 94),

('Bougie Herbe Fraîche', 'L\'odeur vivifiante de l\'herbe fraîchement coupée pour une ambiance printanière permanente.', 'Le Mans', 'Cire de colza', '[{"taille": "S", "prix": 14.90, "barre": 18.90, "combustion": 24, "stock": 19}, {"taille": "M", "prix": 21.90, "combustion": 44, "stock": 13}, {"taille": "L", "prix": 28.90, "combustion": 64, "stock": 9}]', 'Cire de colza française, mèche en coton bio, accord vert d\'herbe fraîche et rosée du matin.', 'Taille S : 24h de combustion\nTaille M : 44h de combustion\nTaille L : 64h de combustion', 'Livraison rapide. Emballage nature. Fabrication artisanale sarthoise.', 1, NOW(), NOW(), 4, NULL, 24, 64),

('Bougie Amande Douce', 'Un parfum délicat et réconfortant d\'amande qui évoque la douceur et la gourmandise.', 'Nice', 'Cire de soja', '[{"taille": "S", "prix": 16.50, "combustion": 26, "stock": 16}, {"taille": "M", "prix": 24.50, "barre": 29.50, "combustion": 46, "stock": 10}, {"taille": "L", "prix": 32.50, "combustion": 66, "stock": 6}]', 'Cire de soja naturelle, mèche en coton, huile d\'amande douce et essence de frangipane.', 'Taille S : 26h de combustion\nTaille M : 46h de combustion\nTaille L : 66h de combustion', 'Livraison Côte d\'Azur et France. Emballage gourmand. Artisanat niçois.', 1, NOW(), NOW(), 3, NULL, 26, 66),

('Bougie Iris & Freesia', 'Un bouquet floral raffiné et poudré qui apporte élégance et sophistication.', 'Nantes', 'Cire végétale', '[{"taille": "S", "prix": 17.50, "barre": 21.50, "combustion": 27, "stock": 14}, {"taille": "M", "prix": 25.50, "combustion": 47, "stock": 9}, {"taille": "L", "prix": 33.50, "barre": 39.50, "combustion": 67, "stock": 5}]', 'Cire végétale premium, mèche en lin, essences d\'iris de Florence et freesia blanc.', 'Taille S : 27h de combustion\nTaille M : 47h de combustion\nTaille L : 67h de combustion', 'Expédition soignée. Emballage floral. Production artisanale nantaise raffinée.', 1, NOW(), NOW(), 1, 6, 27, 67),

('Bougie Cèdre & Bergamote', 'Une harmonie boisée et citrée qui crée une atmosphère apaisante et équilibrée.', 'Besançon', 'Cire de soja', '[{"taille": "M", "prix": 22.90, "combustion": 45, "stock": 11}, {"taille": "L", "prix": 29.90, "barre": 34.90, "combustion": 65, "stock": 7}, {"taille": "XL", "prix": 38.90, "combustion": 88, "stock": 4}]', 'Cire de soja bio, mèche en coton, essence de cèdre de Virginie et bergamote de Calabre.', 'Taille M : 45h de combustion\nTaille L : 65h de combustion\nTaille XL : 88h de combustion', 'Livraison en France. Emballage écologique. Fabrication artisanale comtoise.', 1, NOW(), NOW(), 2, NULL, 45, 88),

('Bougie Cassis & Feuille de Figuier', 'Une composition fruité-verte originale qui marie la gourmandise du cassis à la fraîcheur du figuier.', 'Dijon', 'Cire de colza', '[{"taille": "S", "prix": 15.90, "barre": 19.90, "combustion": 25, "stock": 17}, {"taille": "M", "prix": 23.90, "combustion": 45, "stock": 11}, {"taille": "L", "prix": 31.90, "barre": 37.90, "combustion": 65, "stock": 7}]', 'Cire de colza bourguignonne, mèche en coton, cassis noir de Bourgogne et feuilles de figuier.', 'Taille S : 25h de combustion\nTaille M : 45h de combustion\nTaille L : 65h de combustion', 'Livraison rapide. Emballage bourguignon. Savoir-faire artisanal dijonnais.', 1, NOW(), NOW(), 1, 4, 25, 65),

('Bougie Pomme Verte', 'La fraîcheur croquante de la pomme verte pour une ambiance tonique et vivifiante.', 'Caen', 'Cire de soja', '[{"taille": "S", "prix": 14.50, "combustion": 23, "stock": 18}, {"taille": "M", "prix": 21.50, "barre": 26.50, "combustion": 43, "stock": 12}, {"taille": "L", "prix": 28.50, "combustion": 63, "stock": 8}]', 'Cire de soja naturelle, mèche en coton, essence de pomme verte de Normandie.', 'Taille S : 23h de combustion\nTaille M : 43h de combustion\nTaille L : 63h de combustion', 'Livraison soignée. Emballage normand. Production artisanale du terroir.', 1, NOW(), NOW(), 3, NULL, 23, 63),

('Bougie Pêche de Vigne', 'Un parfum fruité et velouté de pêche mûre gorgée de soleil pour une ambiance estivale.', 'Montauban', 'Cire végétale', '[{"taille": "S", "prix": 16.50, "barre": 20.50, "combustion": 26, "stock": 15}, {"taille": "M", "prix": 24.50, "combustion": 46, "stock": 9}, {"taille": "L", "prix": 32.50, "barre": 38.50, "combustion": 66, "stock": 5}]', 'Cire végétale naturelle, mèche en lin, essence de pêche de vigne du Tarn-et-Garonne.', 'Taille S : 26h de combustion\nTaille M : 46h de combustion\nTaille L : 66h de combustion', 'Expédition rapide. Emballage fruité. Artisanat occitan de qualité.', 1, NOW(), NOW(), 3, NULL, 26, 66),

('Bougie Gingembre & Cardamome', 'Un mélange épicé et chaleureux qui stimule et réchauffe l\'atmosphère.', 'Toulouse', 'Cire de coco', '[{"taille": "M", "prix": 23.50, "combustion": 46, "stock": 10}, {"taille": "L", "prix": 30.50, "barre": 36.50, "combustion": 66, "stock": 6}, {"taille": "XL", "prix": 40.50, "combustion": 90, "stock": 3}]', 'Cire de coco naturelle, mèche en chanvre, racine de gingembre frais et graines de cardamome verte.', 'Taille M : 46h de combustion\nTaille L : 66h de combustion\nTaille XL : 90h de combustion', 'Livraison en France. Emballage épicé. Production artisanale toulousaine.', 1, NOW(), NOW(), 2, NULL, 46, 90),

('Bougie Mimosa & Amande', 'Une association solaire et gourmande qui célèbre le printemps et la douceur méditerranéenne.', 'Cannes', 'Cire de soja', '[{"taille": "S", "prix": 17.90, "barre": 22.90, "combustion": 28, "stock": 13}, {"taille": "M", "prix": 25.90, "combustion": 48, "stock": 8}, {"taille": "L", "prix": 33.90, "barre": 39.90, "combustion": 68, "stock": 4}]', 'Cire de soja bio, mèche en coton, essence de mimosa du Tanneron et amande de Provence.', 'Taille S : 28h de combustion\nTaille M : 48h de combustion\nTaille L : 68h de combustion', 'Livraison Côte d\'Azur et France. Emballage printanier. Artisanat cannois raffiné.', 1, NOW(), NOW(), 1, 2, 28, 68),

('Bougie Cuir & Épices', 'Un parfum masculin et puissant aux notes de cuir noble relevées d\'épices orientales.', 'Saint-Étienne', 'Cire végétale premium', '[{"taille": "M", "prix": 27.90, "combustion": 49, "stock": 8}, {"taille": "L", "prix": 35.90, "barre": 42.90, "combustion": 69, "stock": 5}, {"taille": "XL", "prix": 45.90, "combustion": 93, "stock": 2}]', 'Cire végétale de luxe, mèche en bois, accord cuir espagnol, safran et poivre noir.', 'Taille M : 49h de combustion\nTaille L : 69h de combustion\nTaille XL : 93h de combustion', 'Livraison premium. Emballage masculin. Collection prestige stéphanoise.', 1, NOW(), NOW(), 2, NULL, 49, 93),

('Bougie Figue Fraîche', 'Le parfum lacté et vert de la figue fraîche pour une ambiance méditerranéenne authentique.', 'Montpellier', 'Cire de colza', '[{"taille": "S", "prix": 15.90, "combustion": 25, "stock": 16}, {"taille": "M", "prix": 23.90, "barre": 28.90, "combustion": 45, "stock": 10}, {"taille": "L", "prix": 31.90, "combustion": 65, "stock": 7}]', 'Cire de colza bio, mèche en coton, extrait de figue fraîche et feuilles de figuier.', 'Taille S : 25h de combustion\nTaille M : 45h de combustion\nTaille L : 65h de combustion', 'Livraison rapide. Emballage méditerranéen. Fabrication artisanale héraultaise.', 1, NOW(), NOW(), 1, 3, 25, 65),

('Bougie Mousse de Chêne', 'Un parfum boisé et mousseux qui évoque les promenades en forêt ancienne.', 'Fontainebleau', 'Cire de soja', '[{"taille": "S", "prix": 16.50, "barre": 20.50, "combustion": 26, "stock": 15}, {"taille": "M", "prix": 24.50, "combustion": 46, "stock": 9}, {"taille": "L", "prix": 32.50, "barre": 38.50, "combustion": 66, "stock": 5}]', 'Cire de soja naturelle, mèche en coton bio, accord de mousse de chêne et écorce.', 'Taille S : 26h de combustion\nTaille M : 46h de combustion\nTaille L : 66h de combustion', 'Expédition soignée. Emballage forestier. Artisanat d\'Île-de-France.', 1, NOW(), NOW(), 4, NULL, 26, 66),

('Bougie Violette de Toulouse', 'Le parfum délicat et légèrement poudré de la célèbre violette emblématique de la ville rose.', 'Toulouse', 'Cire végétale', '[{"taille": "S", "prix": 17.50, "combustion": 27, "stock": 14}, {"taille": "M", "prix": 25.50, "barre": 30.50, "combustion": 47, "stock": 8}, {"taille": "L", "prix": 33.50, "combustion": 67, "stock": 5}]', 'Cire végétale fine, mèche en lin, essence absolue de violette de Toulouse.', 'Taille S : 27h de combustion\nTaille M : 47h de combustion\nTaille L : 67h de combustion', 'Livraison France métropolitaine. Emballage violet. Savoir-faire toulousain historique.', 1, NOW(), NOW(), 1, 5, 27, 67),

('Bougie Tilleul en Fleur', 'Le parfum apaisant et miellé des fleurs de tilleul pour des nuits paisibles et sereines.', 'Chambéry', 'Cire de coco', '[{"taille": "M", "prix": 21.90, "combustion": 44, "stock": 11}, {"taille": "L", "prix": 28.90, "barre": 33.90, "combustion": 64, "stock": 7}, {"taille": "XL", "prix": 37.90, "combustion": 87, "stock": 4}]', 'Cire de coco naturelle, mèche en coton, fleurs de tilleul séchées et miel de montagne.', 'Taille M : 44h de combustion\nTaille L : 64h de combustion\nTaille XL : 87h de combustion', 'Livraison en France. Emballage apaisant. Production artisanale savoyarde.', 1, NOW(), NOW(), 4, NULL, 44, 87);

